common: &default_settings
  license_key: <%= ENV['NEW_RELIC_LICENSE_KEY'] %>
  log_level: info

development:
  <<: *default_settings
  app_name: SpaceSkout (Development)
  developer_mode: true

test:
  <<: *default_settings
  monitor_mode: false

staging:
  <<: *default_settings
  app_name: SpaceSkout (Staging)

production:
  <<: *default_settings
  app_name: SpaceSkout
